name: pipeline_facebook_ads
version: "1.0"
config-version: 2

profile: pipeline_facebook_ads

model-paths: ["models"]
macro-paths: ["macros"]

models:
  pipeline_facebook_ads:
    stg:
      +materialized: ephemeral
    int:
      +materialized: ephemeral
    mart:
      +materialized: table
      +tags: ["mart"]

vars:
  company: "{{ env_var('COMPANY') }}"
  department: "{{ env_var('DEPARTMENT') }}"
  account: "{{ env_var('ACCOUNT') }}"